
#-------------------------------------------------------------------------
# GLIMMER architecture-specific configuration file                       |
#                                                                        |
# NAG COMPILER                                                           |
#-------------------------------------------------------------------------

# Check GLIMMER_PREFIX ---------------------------------------------------

ifndef GLIMMER_PREFIX
GLIMMER_PREFIX=../../
endif

# Fortran compiler to use ------------------------------------------------

F77=f95

# netcdf library location ------------------------------------------------
# This may have to be installed from:
# http://www.unidata.ucar.edu/packages/netcdf/index.html

NETCDF_LIB=-lnetcdf
NETCDF_PREFIX=/home/mhagdorn/gnu-Linux

# compilation flags for fortran compiler ---------------------------------

F77FLAGS=-fpp -gline -C -I$(NETCDF_PREFIX)/lib/modules
F77FLAGS=-fpp -I$(NETCDF_PREFIX)/lib/modules

# for SLAP ---------------------------------------------------------------

GLIMMERFLAGS=-dusty

# final stage loader flags -----------------------------------------------

LD_FLAGS=-L$(NETCDF_PREFIX)/lib $(NETCDF_LIB)

# ranlib command, leave blank for no ranlib ------------------------------

RANLIB=ranlib

# Pattern-matching compilation commands ----------------------------------

.c.o:
	$(CC) -c $(CCFLAGS) $< -o $@

.f.o:
	$(F77) -c $(F77FLAGS) $< -o $@

.f90.o:
	$(F77) -c $(F77FLAGS) $< -o $@

%.o : %.mod

.SUFFIXES:      .f .f90 .o
