
#-------------------------------------------------------------------------
# GLIMMER architecture-specific configuration file                       |
#                                                                        |
# INTEL FORTRAN COMPILER (ifort, formerly ifc)                           |
#-------------------------------------------------------------------------

# Check GLIMMER_PREFIX ---------------------------------------------------

ifndef GLIMMER_PREFIX
GLIMMER_PREFIX=../../
endif

# Fortran compiler to use ------------------------------------------------

F77=ifort

# netcdf library location ------------------------------------------------
# This may have to be installed from:
# http://www.unidata.ucar.edu/packages/netcdf/index.html

NETCDF_LIB=-lnetcdf
NETCDF_PREFIX=/usr/local/netcdf-3.5.1

# compilation flags for fortran compiler ---------------------------------

F77FLAGS=-fpp -g -w -std95 -I$(NETCDF_PREFIX)/include

# for SLAP ---------------------------------------------------------------

GLIMMERFLAGS=

# final stage loader flags -----------------------------------------------

LD_FLAGS=-L$(NETCDF_PREFIX)/lib $(NETCDF_LIB)

# ranlib command, leave blank for no ranlib ------------------------------

RANLIB=ranlib

# Pattern-matching compilation commands ----------------------------------

.c.o:
	$(CC) -c $(CCFLAGS) $*.c

.f.o:
	$(F77) -c $(F77FLAGS) $< -o $@

.f90.o:
	$(F77) -c $(F77FLAGS) $< -o $@

%.o : %.mod

.SUFFIXES:	.f .f90 .o
