!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! WARNING: this file was automatically generated on
! Wed, 12 Jan 2005 11:34:20 +0000
! from ncdf_params.f90.in
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

! +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
! +                                                           +
! +  glimmer_outp.f90 - part of the GLIMMER ice model         + 
! +                                                           +
! +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
! 
! Copyright (C) 2004 GLIMMER contributors - see COPYRIGHT file 
! for list of contributors.
!
! This program is free software; you can redistribute it and/or 
! modify it under the terms of the GNU General Public License as 
! published by the Free Software Foundation; either version 2 of 
! the License, or (at your option) any later version.
!
! This program is distributed in the hope that it will be useful, 
! but WITHOUT ANY WARRANTY; without even the implied warranty of 
! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
! GNU General Public License for more details.
!
! You should have received a copy of the GNU General Public License 
! along with this program; if not, write to the Free Software 
! Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 
! 02111-1307 USA
!
! GLIMMER is maintained by:
!
! Ian Rutt
! School of Geographical Sciences
! University of Bristol
! University Road
! Bristol
! BS8 1SS
! UK
!
! email: <i.c.rutt@bristol.ac.uk> or <ian.rutt@physics.org>
!
! GLIMMER is hosted on NeSCForge:
!
! http://forge.nesc.ac.uk/projects/glimmer/
!
! +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

module glimmer_ncparams
  !*FD read netCDF I/O related configuration files
  !*FD written by Magnus Hagdorn, May 2004
  use glimmer_ncdf, only: glimmer_nc_meta
    
  private
  public :: ReadNCParams

  type(glimmer_nc_meta),save :: default_metadata

contains
  subroutine ReadNCParams(model)
    !*FD read netCDF I/O related configuration file
    use glimmer_types
    use glimmer_config
    implicit none
    type(glimmer_global_type) :: model
    
    ! local variables
    type(ConfigSection), pointer :: config
    type(ConfigSection), pointer :: section
    type(glimmer_nc_output), pointer :: output => null()
    type(glimmer_nc_input), pointer :: input => null()

    ! read configuration
    call ConfigRead(model%funits%ncfile,config)

    ! get default meta data
    call GetSection(config,section,'default')
    if (associated(section)) then
       call handle_metadata(section, default_metadata, .true.)
    end if

    ! setup outputs
    call GetSection(config,section,'output')
    do while(associated(section))
       output => handle_output(section,output)
       if (.not.associated(model%funits%out_first)) then
          model%funits%out_first => output
       end if
       call GetSection(section%next,section,'output')
    end do

    ! setup inputs
    call GetSection(config,section,'input')
    do while(associated(section))
       input => handle_input(section,input)
       if (.not.associated(model%funits%in_first)) then
          model%funits%in_first => input
       end if
       call GetSection(section%next,section,'input')
    end do

  end subroutine ReadNCParams

  !==================================================================================
  ! private procedures
  !==================================================================================

  subroutine handle_metadata(section,metadata, default)
    use glimmer_ncdf
    use glimmer_config
    use glimmer_global, only: glimmer_version
    implicit none
    type(ConfigSection), pointer :: section
    type(glimmer_nc_meta) ::metadata
    logical :: default

    ! local variables
    character(len=8) :: date
    character(len=10) :: time

    if (.not.default) then
       metadata%title = trim(default_metadata%title)
       metadata%institution = trim(default_metadata%institution)
       metadata%references = trim(default_metadata%references)
       metadata%comment = trim(default_metadata%comment)
    end if

    call GetValue(section,'title',metadata%title)
    call GetValue(section,'institution',metadata%institution)
    call GetValue(section,'references',metadata%references)
    call GetValue(section,'comment',metadata%comment)

    if (default) then
       call date_and_time(date,time)
       metadata%source = 'Generated by '//trim(glimmer_version)
       write(metadata%history,fmt="(a4,'-',a2,'-',a2,' ',a2,':',a2,':',a6,' : ',a)") date(1:4),date(5:6),date(7:8),&
            time(1:2),time(3:4),time(5:10),trim(glimmer_version)
    else
       metadata%source = trim(default_metadata%source)
       metadata%history = trim(default_metadata%history)
    end if
  end subroutine handle_metadata

  function handle_output(section, output)
    use glimmer_ncdf
    use glimmer_config
    use glide_messages
    implicit none
    type(ConfigSection), pointer :: section
    type(glimmer_nc_output), pointer :: output
    type(glimmer_nc_output), pointer :: handle_output

    ! local variables
    character(len=210) vars
    integer :: numspots=-1
    character(80) :: outtxt

    handle_output=>add(output)
    
    ! get filename
    call GetValue(section,'name',handle_output%nc%filename)
    call GetValue(section,'frequency',handle_output%freq)
    call GetValue(section,'variables',vars)
    call GetValue(section,'numspot',numspots)
    if (numspots.eq.-1) then
       numspots=100
    end if
    call GetValue(section,'spotx',handle_output%spotx,numspots)
    call GetValue(section,'spoty',handle_output%spoty,numspots)

    ! get metadata
    call handle_metadata(section, handle_output%metadata,.false.)

    if (associated(handle_output%spotx) .and. associated(handle_output%spoty)) then
       if (size(handle_output%spotx).ne.size(handle_output%spoty)) then
          write(outtxt,*)size(handle_output%spotx), size(handle_output%spoty)
          call glide_msg(GM_WARNING,__FILE__,__LINE__,&
            '[netCDF output] number of spot x and y locations differ '//trim(outtxt))
       else
          handle_output%nc%do_spot = .true.
       end if
    end if
    
    vars = ' '//trim(vars)//' '

    if (handle_output%nc%filename(1:1).eq.' ') then
       call glide_msg(GM_FATAL,__FILE__,__LINE__,'Error, no file name specified [netCDF output]')
    end if

    ! select which variables should be written
    if (index(vars,' ablt ').ne.0) then
       handle_output%nc%do_var(NC_B_ABLT) = .true.
    end if

    if (index(vars,' ablt_spot ').ne.0 .and. handle_output%nc%do_spot) then
       handle_output%nc%do_var(NC_B_ABLT_SPOT) = .true.
    end if

    if (index(vars,' acab ').ne.0) then
       handle_output%nc%do_var(NC_B_ACAB) = .true.
    end if

    if (index(vars,' acab_spot ').ne.0 .and. handle_output%nc%do_spot) then
       handle_output%nc%do_var(NC_B_ACAB_SPOT) = .true.
    end if

    if (index(vars,' arng ').ne.0) then
       handle_output%nc%do_var(NC_B_ARNG) = .true.
    end if

    if (index(vars,' arng_spot ').ne.0 .and. handle_output%nc%do_spot) then
       handle_output%nc%do_var(NC_B_ARNG_SPOT) = .true.
    end if

    if (index(vars,' artm ').ne.0) then
       handle_output%nc%do_var(NC_B_ARTM) = .true.
    end if

    if (index(vars,' artm_spot ').ne.0 .and. handle_output%nc%do_spot) then
       handle_output%nc%do_var(NC_B_ARTM_SPOT) = .true.
    end if

    if (index(vars,' bmlt ').ne.0) then
       handle_output%nc%do_var(NC_B_BMLT) = .true.
    end if

    if (index(vars,' bmlt_spot ').ne.0 .and. handle_output%nc%do_spot) then
       handle_output%nc%do_var(NC_B_BMLT_SPOT) = .true.
    end if

    if (index(vars,' btemp ').ne.0) then
       handle_output%nc%do_var(NC_B_BTEMP) = .true.
    end if

    if (index(vars,' btemp_spot ').ne.0 .and. handle_output%nc%do_spot) then
       handle_output%nc%do_var(NC_B_BTEMP_SPOT) = .true.
    end if

    if (index(vars,' btrc ').ne.0) then
       handle_output%nc%do_var(NC_B_BTRC) = .true.
    end if

    if (index(vars,' btrc_spot ').ne.0 .and. handle_output%nc%do_spot) then
       handle_output%nc%do_var(NC_B_BTRC_SPOT) = .true.
    end if

    if (index(vars,' bwat ').ne.0) then
       handle_output%nc%do_var(NC_B_BWAT) = .true.
    end if

    if (index(vars,' bwat_spot ').ne.0 .and. handle_output%nc%do_spot) then
       handle_output%nc%do_var(NC_B_BWAT_SPOT) = .true.
    end if

    if (index(vars,' diffu ').ne.0) then
       handle_output%nc%do_var(NC_B_DIFFU) = .true.
    end if

    if (index(vars,' diffu_spot ').ne.0 .and. handle_output%nc%do_spot) then
       handle_output%nc%do_var(NC_B_DIFFU_SPOT) = .true.
    end if

    if (index(vars,' dusrfdtm ').ne.0) then
       handle_output%nc%do_var(NC_B_DUSRFDTM) = .true.
    end if

    if (index(vars,' dusrfdtm_spot ').ne.0 .and. handle_output%nc%do_spot) then
       handle_output%nc%do_var(NC_B_DUSRFDTM_SPOT) = .true.
    end if

    if (index(vars,' flwa ').ne.0) then
       handle_output%nc%do_var(NC_B_FLWA) = .true.
    end if

    if (index(vars,' flwa_spot ').ne.0 .and. handle_output%nc%do_spot) then
       handle_output%nc%do_var(NC_B_FLWA_SPOT) = .true.
    end if

    if (index(vars,' lat ').ne.0) then
       handle_output%nc%do_var(NC_B_LAT) = .true.
    end if

    if (index(vars,' lat_spot ').ne.0 .and. handle_output%nc%do_spot) then
       handle_output%nc%do_var(NC_B_LAT_SPOT) = .true.
    end if

    if (index(vars,' lon ').ne.0) then
       handle_output%nc%do_var(NC_B_LON) = .true.
    end if

    if (index(vars,' lon_spot ').ne.0 .and. handle_output%nc%do_spot) then
       handle_output%nc%do_var(NC_B_LON_SPOT) = .true.
    end if

    if (index(vars,' lsurf ').ne.0) then
       handle_output%nc%do_var(NC_B_LSURF) = .true.
    end if

    if (index(vars,' lsurf_spot ').ne.0 .and. handle_output%nc%do_spot) then
       handle_output%nc%do_var(NC_B_LSURF_SPOT) = .true.
    end if

    if (index(vars,' mask ').ne.0) then
       handle_output%nc%do_var(NC_B_MASK) = .true.
    end if

    if (index(vars,' mask_spot ').ne.0 .and. handle_output%nc%do_spot) then
       handle_output%nc%do_var(NC_B_MASK_SPOT) = .true.
    end if

    if (index(vars,' prcp ').ne.0) then
       handle_output%nc%do_var(NC_B_PRCP) = .true.
    end if

    if (index(vars,' prcp_spot ').ne.0 .and. handle_output%nc%do_spot) then
       handle_output%nc%do_var(NC_B_PRCP_SPOT) = .true.
    end if

    if (index(vars,' presprcp ').ne.0) then
       handle_output%nc%do_var(NC_B_PRESPRCP) = .true.
    end if

    if (index(vars,' presprcp_spot ').ne.0 .and. handle_output%nc%do_spot) then
       handle_output%nc%do_var(NC_B_PRESPRCP_SPOT) = .true.
    end if

    if (index(vars,' presusrf ').ne.0) then
       handle_output%nc%do_var(NC_B_PRESUSRF) = .true.
    end if

    if (index(vars,' presusrf_spot ').ne.0 .and. handle_output%nc%do_spot) then
       handle_output%nc%do_var(NC_B_PRESUSRF_SPOT) = .true.
    end if

    if (index(vars,' relx ').ne.0) then
       handle_output%nc%do_var(NC_B_RELX) = .true.
    end if

    if (index(vars,' relx_spot ').ne.0 .and. handle_output%nc%do_spot) then
       handle_output%nc%do_var(NC_B_RELX_SPOT) = .true.
    end if

    if (index(vars,' std_dev ').ne.0) then
       handle_output%nc%do_var(NC_B_STD_DEV) = .true.
    end if

    if (index(vars,' std_dev_spot ').ne.0 .and. handle_output%nc%do_spot) then
       handle_output%nc%do_var(NC_B_STD_DEV_SPOT) = .true.
    end if

    if (index(vars,' temp ').ne.0) then
       handle_output%nc%do_var(NC_B_TEMP) = .true.
    end if

    if (index(vars,' temp_spot ').ne.0 .and. handle_output%nc%do_spot) then
       handle_output%nc%do_var(NC_B_TEMP_SPOT) = .true.
    end if

    if (index(vars,' thk ').ne.0) then
       handle_output%nc%do_var(NC_B_THK) = .true.
    end if

    if (index(vars,' thk_spot ').ne.0 .and. handle_output%nc%do_spot) then
       handle_output%nc%do_var(NC_B_THK_SPOT) = .true.
    end if

    if (index(vars,' topg ').ne.0) then
       handle_output%nc%do_var(NC_B_TOPG) = .true.
    end if

    if (index(vars,' topg_spot ').ne.0 .and. handle_output%nc%do_spot) then
       handle_output%nc%do_var(NC_B_TOPG_SPOT) = .true.
    end if

    if (index(vars,' ubas ').ne.0) then
       handle_output%nc%do_var(NC_B_UBAS) = .true.
    end if

    if (index(vars,' ubas_spot ').ne.0 .and. handle_output%nc%do_spot) then
       handle_output%nc%do_var(NC_B_UBAS_SPOT) = .true.
    end if

    if (index(vars,' uflx ').ne.0) then
       handle_output%nc%do_var(NC_B_UFLX) = .true.
    end if

    if (index(vars,' uflx_spot ').ne.0 .and. handle_output%nc%do_spot) then
       handle_output%nc%do_var(NC_B_UFLX_SPOT) = .true.
    end if

    if (index(vars,' usurf ').ne.0) then
       handle_output%nc%do_var(NC_B_USURF) = .true.
    end if

    if (index(vars,' usurf_spot ').ne.0 .and. handle_output%nc%do_spot) then
       handle_output%nc%do_var(NC_B_USURF_SPOT) = .true.
    end if

    if (index(vars,' uvel ').ne.0) then
       handle_output%nc%do_var(NC_B_UVEL) = .true.
    end if

    if (index(vars,' uvel_spot ').ne.0 .and. handle_output%nc%do_spot) then
       handle_output%nc%do_var(NC_B_UVEL_SPOT) = .true.
    end if

    if (index(vars,' vbas ').ne.0) then
       handle_output%nc%do_var(NC_B_VBAS) = .true.
    end if

    if (index(vars,' vbas_spot ').ne.0 .and. handle_output%nc%do_spot) then
       handle_output%nc%do_var(NC_B_VBAS_SPOT) = .true.
    end if

    if (index(vars,' vflx ').ne.0) then
       handle_output%nc%do_var(NC_B_VFLX) = .true.
    end if

    if (index(vars,' vflx_spot ').ne.0 .and. handle_output%nc%do_spot) then
       handle_output%nc%do_var(NC_B_VFLX_SPOT) = .true.
    end if

    if (index(vars,' vvel ').ne.0) then
       handle_output%nc%do_var(NC_B_VVEL) = .true.
    end if

    if (index(vars,' vvel_spot ').ne.0 .and. handle_output%nc%do_spot) then
       handle_output%nc%do_var(NC_B_VVEL_SPOT) = .true.
    end if

    if (index(vars,' wgrd ').ne.0) then
       handle_output%nc%do_var(NC_B_WGRD) = .true.
    end if

    if (index(vars,' wgrd_spot ').ne.0 .and. handle_output%nc%do_spot) then
       handle_output%nc%do_var(NC_B_WGRD_SPOT) = .true.
    end if

    if (index(vars,' wvel ').ne.0) then
       handle_output%nc%do_var(NC_B_WVEL) = .true.
    end if

    if (index(vars,' wvel_spot ').ne.0 .and. handle_output%nc%do_spot) then
       handle_output%nc%do_var(NC_B_WVEL_SPOT) = .true.
    end if

  end function handle_output
  
  function handle_input(section, input)
    use glimmer_ncdf
    use glimmer_config
    use glide_messages
    implicit none
    type(ConfigSection), pointer :: section
    type(glimmer_nc_input), pointer :: input
    type(glimmer_nc_input), pointer :: handle_input

    handle_input=>add(input)
    
    ! get filename
    call GetValue(section,'name',handle_input%nc%filename)
    call GetValue(section,'time',handle_input%get_time_slice)
    
    handle_input%current_time = handle_input%get_time_slice

    if (handle_input%nc%filename(1:1).eq.' ') then
       call glide_msg(GM_FATAL,__FILE__,__LINE__,'Error, no file name specified [netCDF input]')
    end if
  end function handle_input
end module glimmer_ncparams
